# Generated by Django 5.0.7 on 2024-07-29 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 5, 48, 51, 209290, tzinfo=datetime.timezone.utc)),
        ),
    ]
