# Generated by Django 5.0.7 on 2024-08-01 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 22, 13, 6, 985201, tzinfo=datetime.timezone.utc)),
        ),
    ]
