# Generated by Django 5.0.7 on 2024-08-04 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 22, 24, 20, 983794, tzinfo=datetime.timezone.utc)),
        ),
    ]
