# Generated by Django 5.0.7 on 2024-08-09 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 16, 53, 21, 761850, tzinfo=datetime.timezone.utc)),
        ),
    ]
