# Generated by Django 5.0.7 on 2024-08-11 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 23, 20, 15, 781768, tzinfo=datetime.timezone.utc)),
        ),
    ]
