# Generated by Django 5.0.7 on 2024-08-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='000000', editable=False, max_length=6, unique=True),
        ),
    ]
