# Generated by Django 5.0.7 on 2024-08-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_order_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
